# Keras
[Examples](https://keras.io/examples/)

```pip install tensorflow```

In [12]:
import tensorflow as tf
from tensorflow import keras

In [15]:
import numpy as np
from sklearn.datasets import load_iris

In [16]:
iris = load_iris()
#print(iris.DESCR)

In [17]:
X = iris.data
y = iris.target

In [18]:
# encode target to one-hot
from keras.utils import to_categorical
y = to_categorical(y)

In [19]:
# Split test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

# Preprocessing
from sklearn.preprocessing import MinMaxScaler
scaler_object = MinMaxScaler()
scaler_object.fit(X_train)
scaled_X_train = scaler_object.transform(X_train)
scaled_X_test = scaler_object.transform(X_test)

In [20]:
# Building Network 
from keras.models import Sequential
from keras.layers import Dense

model = Sequential()
model.add(Dense(8, input_dim=4, activation='relu')) # Input layer
model.add(Dense(8, input_dim=4, activation='relu')) # Hidden layer
model.add(Dense(3, activation='softmax')) # Output layer
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 8)                 40        
_________________________________________________________________
dense_1 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_2 (Dense)              (None, 3)                 27        
Total params: 139
Trainable params: 139
Non-trainable params: 0
_________________________________________________________________


In [22]:
# Train and Predict
model.fit(scaled_X_train,y_train,epochs=200, verbose=1)

# Spits out probabilities by default.
# predictions = model.predict(scaled_X_test)
predictions = model.predict_classes(scaled_X_test)

Epoch 1/200
4/4 [==============================] - 0s 2ms/step - loss: 0.4351 - accuracy: 0.8200
Epoch 2/200
4/4 [==============================] - 0s 3ms/step - loss: 0.4342 - accuracy: 0.8400
Epoch 3/200
4/4 [==============================] - 0s 3ms/step - loss: 0.4330 - accuracy: 0.8500
Epoch 4/200
4/4 [==============================] - 0s 3ms/step - loss: 0.4320 - accuracy: 0.8200
Epoch 5/200
4/4 [==============================] - 0s 5ms/step - loss: 0.4308 - accuracy: 0.8100
Epoch 6/200
4/4 [==============================] - 0s 3ms/step - loss: 0.4301 - accuracy: 0.7900
Epoch 7/200
4/4 [==============================] - 0s 3ms/step - loss: 0.4294 - accuracy: 0.7600
Epoch 8/200
4/4 [==============================] - 0s 3ms/step - loss: 0.4289 - accuracy: 0.7400
Epoch 9/200
4/4 [==============================] - 0s 8ms/step - loss: 0.4279 - accuracy: 0.7400
Epoch 10/200
4/4 [==============================] - 0s 4ms/step - loss: 0.4268 - accuracy: 0.7400
Epoch 11/200
4/4 [===========

In [23]:
# Evaluate
from sklearn import metrics
# .argmax(axis=1) transform one-hot back to category 
print(metrics.confusion_matrix(y_test.argmax(axis=1),predictions))
print(metrics.classification_report(y_test.argmax(axis=1),predictions))

[[19  0  0]
 [ 0 14  1]
 [ 0  0 16]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.93      0.97        15
           2       0.94      1.00      0.97        16

    accuracy                           0.98        50
   macro avg       0.98      0.98      0.98        50
weighted avg       0.98      0.98      0.98        50



In [ ]:
# Save
model.save('myfirstmodel.h5')

In [ ]:
# Load
from keras.models import load_model
newmodel = load_model('myfirstmodel.h5')
newmodel.predict_classes(scaled_X_test)

## Learning curves

**error (dev set, train set) vs m (training set size)** : tells if more data is needed to reach acceptable level of error




### Reducing Bias
- Increase the model size
- Add features aim at the bias
- Reduce regularization
- Modify model architecture

### Reducing variance
- Add more data
- Add regularization
- Early stopping (decrease tolerance)
- Feature selection (reduction)
- Decrease model size